language: python
python:
  - "3.4"
sudo: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install: python setup.py install
script: python spec.py
virtualenv:
  system_site_packages: true
notifications:
  email:
    - ne2210@columbia.edu